########################################
##      Fly Reservation System        ##
########################################
# Docker system composition descriptor #
########################################
# Author: Génovèse Matthieu           #
# Version: 1.0                         #
########################################

## Start the system with "docker-compose up -d"
## Shutdown it with "docker-compose down"
## To clean your docker install: "docker system prune"
## To purge your docker install: "docker system prune -a"

version: '3'

services:

  cars-hotels-reservation:
    container_name: cars-hotels-reservation
    image: travelagency/cars-hotels-reservation-rest
    ports:
      - "9090:8080"
      
  flyreservation-registry:               # Fly reservation registry, on port 9080
    container_name: flyreservation
    image: travelagency/flyreservation-document
    depends_on:
      - database
    ports:
      - "9080:8080"
      
  database:                       # MongoDB database, on port 27017
    container_name: tcs-database
    image: mongo:3.0
    volumes:
      - "./mongo_data:/data/db"
    ports:
      - "27547:27547"
